services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wp_vol:/var/www/html
    restart: on-failure
    
  wordpress:
    # image: demyx/wordpress
    build: ./requirements/wordpress/
    volumes:
      - wp_vol:/var/www/html
    environment:
      WORDPRESS_URL: ${DOMAIN_NAME}
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    restart: on-failure

  mariadb:
    # image: yobasystems/alpine-mariadb
    build: ./requirements/mariadb/
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: on-failure
  
volumes:
  wp_vol:
