services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wp_vol:/var/www/html
    restart: on-failure
    
  wordpress:
    build: ./requirements/wordpress/
    volumes:
      - wp_vol:/var/www/html
    environment:
      WORDPRESS_URL: ${DOMAIN_NAME}
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb/
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: on-failure
  
  volumes:
    db_vol:
      driver: local
      driver_opts:
        type: none
        device: /home/ncastell/data/db_vol
        o: bind
    wp_vol:
      driver: local
      driver_opts:
        type: none
        device: /home/ncastell/data/wp_vol
        o: bind
